### ISSUE TITLE
Add specific color for #pragma message

### ISSUE THREAD

**Issue by xNiux** [IARSystems/iar-vsc-build#24]
Hi, to have more visual message during compilation, it could be very useful to have a dedicated color (ex: Yellow) when pragma message is displayed during compilation : 

![image](https://user-images.githubusercontent.com/25155398/185895161-19cd82c8-013a-40d6-acfd-2f6ae1997abd.png)

![image](https://user-images.githubusercontent.com/25155398/185895232-e92ff7de-761e-47ea-adb0-b443e2fc2f9c.png)

**Comment by xNiux** [comment]
To simplify, maybe the using keyword like "INFO" in the pragma could be a good solution : 

`#pragma message ("INFO: This is a debug version, do not use for production ....") ;`

**Comment by HampusAdolfsson** [comment]
We can definitely add some color to highlight any line that starts with "INFO" (or "#").

Highlighting *any* pragma messages isn't really possible just from the VS Code extension, since we don't have any information about what caused each line to be printed. It would have to be added in the compiler itself (which is a bit more complicated).

**Comment by HampusAdolfsson** [comment]
Sorry for the late feedback on this. We've decided not to implement this feature. This is something that should be implemented in the compiler rather than adding a half-measure solution to the VS Code extension.
