### ISSUE TITLE
Feature : Compile output on VS code output window

### ISSUE THREAD

**Issue by xNiux** [IARSystems/iar-vsc-build#4]
It could be very usefull to have the compilation output on VSCode Output tabs instaed of Terminal one.
==> Output tabs could be use color to highlight Error, Warning and others ...

For example, I combined this 2 extensions : 
- [https://marketplace.visualstudio.com/items?itemName=zip696.iar-tool](https://marketplace.visualstudio.com/items?itemName=zip696.iar-tool)
- [https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer](https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer)

![image](https://user-images.githubusercontent.com/25155398/174062318-75fb1ab5-6fc3-45b8-95d2-2c9a0d3c930c.png)

And the error is highlight in RED, and Warning in Orange. It is really cool :)

**Comment by HampusAdolfsson** [comment]
I really like the idea of having colorized output for building.

Since this extension uses `Task`s for compilation/build jobs, I'm not sure if there is a "good" way to have it output to the Output tab instead of the Terminal. I think a better solution is to inject terminal escape codes to stylize the build output in the Terminal tab. I'll experiment a bit with scanning the build output and adding some color to it.

**Comment by xNiux** [comment]
Great! It's sounds vert well!

Le ven. 17 juin 2022 à 15:57, Hampus Adolfsson ***@***.***> a
écrit :

**Comment by HampusAdolfsson** [comment]
This is now released.
There might be room for improvement in the future, but for now we highlight:
* Files
* Errors/Warnings
* Error/warning codes
