### ISSUE TITLE
The "Project To Exclude" configuration option is essentially unusable and not sufficiently documented

### ISSUE THREAD

**Issue by jwbmwv** [IARSystems/iar-vsc-build#41]
A project I inherited includes a vendor sdk that has a plethora of ewp files I need to exclude to preserve sanity (both NXP and ST tend to do this). I am not afforded the option of pruning them from our repository. The issue is startup time for opening a folder becomes ridiculous coupled with the unwanted searching for the correct project in the dropdown.

I cannot manage to construct a proper regex to do this. In this case, it would be useful to be able to ignore (or not search) one or more designated directory trees. I can't imagine this is a unique problem. I have seen other extensions that make this sort of option more user friendly.

**Comment by HampusAdolfsson** [comment]
I agree that the option is confusing and impractical. In the future we will implement support for Embedded Workbench workspaces in VS Code, which would make this option obsolete since you could use the eww file to specify which projects you care about (see #35). We'll have a look at whether there are any simple improvements we could do to this option in the meantime.

Some things to keep in mind:
* The regex is tested against the *absolute* path of each ewp file.
* Since this is a regex, backslashes need to be escaped (e.g. `c:\\myDir` in the UI or `c:\\\\myDir` in the settings.json file).
* File paths are case-sensitive even on windows (this is a bug, which I will fix) and use a lower-case drive letter.

Lastly, the "Files: Exclude" VS Code option lets you specify globs of files for VS Code to completely ignore, and they will also be ignored by this extension. If you prefer glob patterns and you're OK with these ewp files being hidden from the explorer view, this is an option (you would need to reload VS Code for this option to take effect).

**Comment by HampusAdolfsson** [comment]
This has been improved in version 1.30.1. It now allows forward slashes on windows and is case-insensitive.

I'll also note that this release includes support for workspace (.eww) files, so you can manage which projects you want to work with using a workspace file instead.
